version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - impactor-network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NASA_API_KEY=${NASA_API_KEY:-DEMO_KEY}
      - USGS_BASE_URL=${USGS_BASE_URL}
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-3600}
      - DEBUG=${DEBUG:-true}
    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on:
      - redis
    networks:
      - impactor-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - impactor-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infra/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - impactor-network

volumes:
  redis_data:

networks:
  impactor-network:
    driver: bridge
